### ISSUE TITLE
[Forum] Last page color should be different from forum post link

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#1]
The last page button color is currently the same as the topic title, making it look like the page number is part of the topic name.

![image](https://user-images.githubusercontent.com/102884856/162769574-5bd97400-683b-492d-a112-009ffae2d5ff.png)

This differs from e621's default theme
![image](https://user-images.githubusercontent.com/102884856/162769527-aa131019-e876-4377-9edd-b9d36ed4f172.png)

Example element:
`<a class="last-page" href="/forum_topics/22535?page=3">page 3</a>`

**Comment by mandorinn** [comment]
Fixeddd~ 
Now the .forum-post-link element uses the "content-link" variables for its color while the .last-page element uses "base-text-faded" for its non hover state and "base-text" for its hover state. Plus some other changes such as making the 'sticky' and 'new' text indicators be icons now~
Am pushing out the update now!


![firefox_LrAPF7htmE](https://user-images.githubusercontent.com/91846001/162827410-e7217e64-cc09-4b98-b17f-d1d0f3df2b31.png)
