### ISSUE TITLE
Forum votes overflow the page

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#11]
Votes for tag relationships on the forums overflow the page if there's too many votes - making it impossible to truthfully see how many people have voted.

![image](https://user-images.githubusercontent.com/102884856/181645107-67d59169-da64-4fa3-a4a4-680ae0ce2e30.png)
![image](https://user-images.githubusercontent.com/102884856/181645144-3f10306c-5086-47ba-9b8f-15f3f3cb1501.png)
https://e621.net/forum_topics/26549

![image](https://user-images.githubusercontent.com/102884856/181645264-79405255-9773-471c-b847-19bad79dd60d.png)
![image](https://user-images.githubusercontent.com/102884856/181645301-e4ced56d-118c-4b9c-ba27-93b46dc71c41.png)
https://e621.net/forum_topics/32215

**Comment by mandorinn** [comment]
Fixed~ A bit surprised I didn't notice this myself because of how *obvious* it is but ya know w/eeeee lmaooo
