### ISSUE TITLE
Active related tags have no highlighting

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#15]
Vanilla e621
![image](https://user-images.githubusercontent.com/102884856/184962708-e85ebf8b-721f-4f3a-9573-571b77ceaf94.png)

eSix Café
![image](https://user-images.githubusercontent.com/102884856/184962772-06ee8beb-60f7-429c-ac4f-e42a16d72f23.png)

The `tag-active` class (seen in the related tags box when editing a post) for some reason doesn't seem to get styled - since this is going to require picking some colors I feel like you'll do a better job than me. Instead of having to change the theme multiple times you can see the colors already used on the site [here](https://github.com/zwagoth/e621ng/pull/415).

Since I know you don't really edit tags you can just paste this into the page for testing: [active-tags.txt](https://github.com/mandorinn/eSix-Cafe/files/9353868/active-tags.txt)

**Comment by mandorinn** [comment]
Should be fixed now! I wouldn't be surprised if it didn't look great on classic Serpent and Hotdog but for the other themes it should be fineee~

**Comment by faucetlol** [comment]
That works pretty great actually!

As for hotdog...

![image](https://user-images.githubusercontent.com/102884856/184980565-09ca175d-6b94-477a-add6-60f9c83798b9.png)

Yeah it doesn't look that great, but I think anybody actually using Hotdog theme is trying to cause themselves permanent ocular nerve damage anyway.

**Comment by mandorinn** [comment]
It looks better than I thought it would tbh! I forgot if --bg-300 was the neon red or the neon yellow lmaooo
Hopefully the theoretical single person using hotdog and also who edits tags frequently enjoys the change~
