### ISSUE TITLE
Menu is missing on mobile layout

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#17]
I finally got around to working out how to install Stylus on Firefox for Android, the menu is missing making the website very difficult to navigate.

Vanilla
![-2147483648_-236921](https://user-images.githubusercontent.com/102884856/185452768-73c37752-357d-44e4-9f48-9ad12ec4f8e8.jpg)

eSix Café
![-2147483648_-236919](https://user-images.githubusercontent.com/102884856/185452752-f232261c-fce4-468c-9774-da7e99c6d0a3.jpg)

_(why are Android screenshots so huge??)_

I'm not sure if it's worth putting much time into mobile version bugs since there's probably very few people actually using it _(maybe only me?)_ but this one seems necessary since it makes the website pretty much unusable. You can even replicate it on desktop by resizing the window small enough (with re621 disabled) so it's probably a simple enough media query.

**Comment by faucetlol** [comment]
Oh, it's [intentionally hidden](https://github.com/mandorinn/eSix-Cafe/blob/main/release/eSixCafe.user.css#L3247-L3249) - I guess because removing that line it ends up with two menus if re621 is installed.

![image](https://user-images.githubusercontent.com/102884856/185455032-72e3d576-9ed3-4985-820f-7c744f8cee75.png)

Considering the menu button doesn't even seem to do anything when RE621 is installed, I wonder if it should be removing that button itself, unless there's some clever CSS solution you can come up with.

**Comment by mandorinn** [comment]
Woke up a few minutes agoooo, didn't sleep 12 hours this time lmaooo 
I *totally* didn't think about what'd happen if re621 wasn't installed on mobile!
Apparently re621 doesn't add <code>data-enhancements</code> to the body anymore, *but* it does add a few others such as <code>data-sticky</code>.
So, *assuming that attribute is always added when re621 is installed,* fixing the nav should be as easy as changing <code>body.resp #maintoggle</code> to <code>body[data-sticky] #maintoggle</code>, hopefully this fix works for you as wellllll!

**Comment by faucetlol** [comment]
Works perfectly!!

**Comment by mandorinn** [comment]
Sickkkkk! Hopefully that attribute doesn't get changed in the future like <code>data-enhancements</code>, tho it'd probably be an easy fix in the future if it doessss lollll

**Comment by faucetlol** [comment]
The hiding it actually only seems to work on the posts page, other pages still have it :(

![image](https://user-images.githubusercontent.com/102884856/186177410-f3711519-4dde-49d1-806b-ed50c5d4867c.png)

Having an extra menu button is still better than users without RE621 getting no menu button at all though... I'm about to make a PR to just incorporate it into RE621 itself because there's really no need to ever have that button there when it has its own menu.

**Comment by bitWolfy** [comment]
> Woke up a few minutes agoooo, didn't sleep 12 hours this time lmaooo I _totally_ didn't think about what'd happen if re621 wasn't installed on mobile! Apparently re621 doesn't add `data-enhancements` to the body anymore, _but_ it does add a few others such as `data-sticky`. So, _assuming that attribute is always added when re621 is installed,_ fixing the nav should be as easy as changing `body.resp #maintoggle` to `body[data-sticky] #maintoggle`, hopefully this fix works for you as wellllll!

@mandorinn Both `data-enhancements` and `data-sticky` are used to turn specific portions of RE621 on and off.
The former toggles the profile page redesign, the latter – sticky search box.
Both are still being used, but neither can be relied on to detect whether RE621 is running or not.

I've added a new `re621` attribute to body in [1.5.41](https://github.com/bitWolfy/re621/releases/tag/1.5.41) that is always set to `true`.
