### ISSUE TITLE
[Help Page] Link list has disappeared

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#2]
Enabling eSix Café seems to make the link list on the [help page](https://e621.net/help) disappear

![image](https://user-images.githubusercontent.com/102884856/162841887-a36611a9-4b64-4163-b31c-d3c75dbada8e.png)

![image](https://user-images.githubusercontent.com/102884856/162841845-23795679-8ad8-4196-8c6d-0bbf804b01f7.png)

It looks like [these lines](https://github.com/mandorinn/eSix-Cafe/blob/82166ffeebfd8d884666f52c8774f35dc53376c6/release/eSixCafe.user.css#L668-L670) are what's doing it.

**Comment by mandorinn** [comment]
Have commented those lines out for now, I can only assume they were left over from me trying to do something funky with the ? link for tags or something. If it wasn't that then I do not remember why that was thereeee
Will leave this issue open for a bit just in case one of us catch any issues that crop uppppp

**Comment by mandorinn** [comment]
I figured out why the code was there in the first place!

It was to get rid of this searching favorites message~
![image](https://user-images.githubusercontent.com/91846001/162851339-21cf89c4-a830-40bd-bbb0-1685fdd555e4.png)
I changed the nth-child selector to a [style="color:darkorange;margin-bottom:0.5rem;"] attribute selector and that fixes 2 things with one stoneeee~
