### ISSUE TITLE
News on homepage isn't styled

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#24]
New addition to the homepage, needs styling.

![image](https://user-images.githubusercontent.com/102884856/191308083-7cdd72c5-67ed-4fb7-8d97-3c61d75368c2.png)

**Comment by mandorinn** [comment]
![image](https://user-images.githubusercontent.com/91846001/191313219-38d1601d-2ef7-4f1f-bb41-8d86ca961365.png)
Should be fixed now!
