### ISSUE TITLE
:has() update: default outline color with classic hexagon too similar to admin?

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#25]
When using classic hexagon theme I think the default avatar border color might be too similar to the admin one, it is a visually different color but I do wonder if it's a little _too_ close. Not seeing any obvious problems in other themes.

![image](https://user-images.githubusercontent.com/102884856/191308810-1020a10a-9b8b-4951-932b-10f4ca3a56f6.png)

**Comment by mandorinn** [comment]
Took *way* too long to get the selectors to work, but now the hexagon borders use the <code>--user-member</code> variable if the ranked border colors option is on, not sure what color would be best thooooo
But we can change that later, for *now*, I think the white works fine!
![image](https://user-images.githubusercontent.com/91846001/191319027-5c490206-edef-4f84-ba6b-66d1ac98aed2.png)

**Comment by faucetlol** [comment]
Looks great, the white actually contrasts really well with the background. Almost makes me want to get demoted back to a regular member 🤔

**Comment by mandorinn** [comment]
You *could* always give yourself a unique border color if ya wantedddd *nudge nudge wink wink*
You'd just need to wrap whatever styling you'd want in like <code>
.author-info:has(a[href="/users/601225"])</code>
Or at least I think that'd work off the top of my headddddd?
