### ISSUE TITLE
[Mobile] User borders don't display correctly on blips page

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#27]
User borders aren't displaying correctly on the mobile version of the blips page.

![image](https://user-images.githubusercontent.com/102884856/198829478-544612ca-1805-4ed2-a9c9-963f1ca93fce.png)
(i always forget how *huge* screenshots on my phone are compared to desktop)

**Comment by faucetlol** [comment]
Actually showing user icons like this seems to be a discrepancy on the blips page, since other pages like comments, forums, etc. all use this layout:

![image](https://user-images.githubusercontent.com/102884856/198830071-dce23c88-8433-4a0c-80d4-eddbe0be75f7.png)

**Comment by mandorinn** [comment]
Just now got the chance to fix it! Hopefully it works fine nowwww!
