### ISSUE TITLE
Replacements notice is weird when the post is also pending

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#28]
When the post is pending and has pending replacements the notice doesn't appear properly
![image](https://user-images.githubusercontent.com/102884856/209788675-273de31c-f95e-4335-9f49-d0aa9c3b26aa.png)

```
<div class="bottom-notices">
        
          

  <div class="notice notice-pending" id="pending-approval-notice">
    This post is pending approval. (<a href="/wiki_pages?title=about%3Amod_queue">learn more</a>)

    

  </div>

  <div class="notice notice-flagged">
    <p>This post has <a href="/post_replacements?search%5Bpost_id%5D=3773468">pending replacements.</a></p>
  </div>

      </div>
```

How it's presumably supposed to look, on a post that's already approved but has pending replacements
![image](https://user-images.githubusercontent.com/102884856/209788653-f27094ab-facc-4ca1-adcf-6dbe6a0473bd.png)

```
<div class="bottom-notices">
        
          


  <div class="notice notice-flagged">
    <p>This post has <a href="/post_replacements?search%5Bpost_id%5D=3639541">pending replacements.</a></p>
  </div>

      </div>
```

Both elements look identical to me so... I'm not sure what's going on here

**Comment by mandorinn** [comment]
Sorry I took so long, was a bit busy todayyyy!
The issue was font size and margins with the before and after elements being weird on posts that were also pending approval, should be fixed nowwww!
