### ISSUE TITLE
[Mobile] Not all tables fit on the screen

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#29]
Going on a hunt for mobile issues, low priority since I generally use the desktop layout on my phone anyways, but sometimes I'm using the mobile layout and encounter problems.

Some tables on the mobile layout aren't showing the full amount of information on the screen due to overflow, while other pages like [/wiki_pages](https://e926.net/wiki_pages) are working just fine. Without eSix Cafe installed it's possible to zoom out or scroll to see the additional information, but eSix Cafe doesn't let you do that.

#### [Wiki Page Versions](https://e926.net/wiki_page_versions)
Desktop
![image](https://user-images.githubusercontent.com/102884856/210339167-91499060-2073-4f9e-971d-796ce5e9628d.png)
Mobile
![image](https://user-images.githubusercontent.com/102884856/210339109-10a5012d-0ed3-4d17-91f9-059677480299.png)

#### [Bulk Update Requests](https://e926.net/bulk_update_requests)
Desktop
![image](https://user-images.githubusercontent.com/102884856/210340397-2bd09536-c8c1-413e-8c8b-e9829202b537.png)
Mobile (also something up with the search options there)
![image](https://user-images.githubusercontent.com/102884856/210340274-78da5cdb-962b-4a20-b7a2-95a53a2dfd02.png)

**Comment by mandorinn** [comment]
Almost forgot the BUR page before closing this issue, just got around to it nowwww!
