### ISSUE TITLE
Tag categories not being colored in all places

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#3]
![image](https://user-images.githubusercontent.com/102884856/163101001-d5caa26d-0930-435d-9140-b95a77578e4f.png)
[Upload page](https://e621.net/uploads/new)

![image](https://user-images.githubusercontent.com/102884856/163101637-2bd1d3fc-ef7f-4f6d-ae21-6bb54a2e3b6a.png)
[Tags page](https://e621.net/tags)

Removing `#sidebar` on [these lines](https://github.com/mandorinn/eSix-Cafe/blob/main/release/eSixCafe.user.css#L681-L716) appears to fix it and I can't imagine it causing any problems in other places.

**Comment by mandorinn** [comment]
Good catch, thank you! Have fixed~ 
I suppose this means I need to finish my tweaks to the help page's sidebar quickly so I can publish the update lolll

Also, in this update I'll include this fix to forum links where the post time is the same brightness as the usernames~
![firefox_yhBFee5pNN](https://user-images.githubusercontent.com/91846001/163102864-fff86c1c-e278-4919-a785-2b03b2a5d7d9.png)

Published! You can check out the update notes hereeeee
https://github.com/mandorinn/eSix-Cafe/commit/513e9df4198045efc4289f3800aab830e5db1cac
