### ISSUE TITLE
[Mobile + re621] Can't search posts because of infinite scrolling

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#30]
It's near impossible to search posts in mobile layout with re621 installed because it puts the search bar after the posts, and trying to scroll to the search bar just loads more posts because of infinite scrolling.

https://user-images.githubusercontent.com/102884856/210344156-6b1b08b0-cf2b-43c4-b318-8b7505ad3523.mp4

**Comment by mandorinn** [comment]
Sorry for the (almost) week late responseeeee, have been a lil busy doing other things and I just now only got to sit down and fix these issues! They *should* be fixed nowwww? Hopefully anyway!
