### ISSUE TITLE
Header logo is gone

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#38]
![image](https://user-images.githubusercontent.com/102884856/229015545-5396508e-170d-4218-a1b6-21eece85b8b8.png)

Maybe I'm just blind, but didn't notice it missing until now.

I assume this relates to https://github.com/re621/re621.Legacy/commit/51d96bb144f832f3578a82207c8826f46f32fdde

**Comment by mandorinn** [comment]
I noticed this like 2 days ago but I was a bit too busy to sit down and fix itttt, had some time tonight to fix the stuff I that I noticed got borked thooooo

Most of the issues were just because of some classes being changed so it was all pretty quick to fix thankfullyyyyy
