### ISSUE TITLE
Blip buttons on own blips are broken

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#40]
![image](https://github.com/mandorinn/eSix-Cafe/assets/102884856/8644fc63-5175-4af3-83e3-ff4bbc41b610)

That's a lot of ats.

**Comment by mandorinn** [comment]
I uh, mighta sorta lost track of time, *woopssss*
Anyway, it should be fixed nowwwww!

Also I fixed the the search autocomplete tags being unstyled when ya stop hovering on themmmm

**Comment by faucetlol** [comment]
That's a hell of a lot better, thanks!

> Also I fixed the the search autocomplete tags being unstyled when ya stop hovering on themmmm

Thanks so much for that also! That's been bothering me for a good while and I kept planning to take the time to fix that myself, but procrastinating too much.
