### ISSUE TITLE
AIBUR votes and forum icons now overlap

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#42]
![image](https://github.com/mandorinn/eSix-Cafe/assets/102884856/3ac1b453-0995-457f-abc6-d9393ce8efd1)

I'm going to guess this relates to the styling changes in https://github.com/e621ng/e621ng/pull/601

**Comment by mandorinn** [comment]
Should be good now, made it so the votes list has a margin-top of 1.5em if buttons are enabled compared to the .5em it has normallyyy!
