### ISSUE TITLE
Icons appearing in body of forum posts

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#43]
![image](https://github.com/mandorinn/eSix-Cafe/assets/102884856/97f37e92-7a40-453b-a384-f62f7e2421fd)
[394058](https://e621.net/forum_posts/394058)

A more precise selector is needed. It seems like the buttons are in a div with the class `content-menu` for both forum posts and comments, but I'm not sure about every part of the site.

**Comment by mandorinn** [comment]
Should be good now? Assuming I'm not misreading any of the other icon pseudo-elements, the edit icon seems to be the only one that relies on the class or href attribute containing a specific word to work compared to the others needing something more complex. 

So for now hopefully just prepending `.content-menu` to those specific selectors is all that's neededddd
