### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by ghost** [mandorinn/eSix-Cafe#50]
Notably:
- Two search bars. The main search bar should be disabled and the mobile one used instead.
- The font size shouldn't be modified on mobile for sidebar or else tag links become hard to click.
- The sidebar ordering shouldn't be modified so that the tags and related can be at the bottom (like e621 does).

The logo in the navbar not being centered and the sub navbar not being colored correctly are minor problems, but would be nice improvements.

Side note: This is also without re621 and I get different results between computer Chromium device simulation and Android outdated Firefox. Outdated Firefox does give same results as Chromium when it comes to e621 so I am just assuming CSS is just giving me trouble.

**Comment by mandorinn** [comment]
Since this is the wordier of the two issues I'll just comment once here, I *think* I got everything listed, plus a few other things I noticeddd!
