### ISSUE TITLE
New wiki page notice not themed

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#6]
![image](https://user-images.githubusercontent.com/102884856/163652181-226900cb-8798-4a61-9358-7badd0bf8250.png)

The notice that appears [while creating a new wiki page](https://e621.net/wiki_pages/new?wiki_page%5Btitle%5D=aaaaaaaaa) uses e621's original colors, showing hotdog bright red while using the hot coffee theme.

**Comment by mandorinn** [comment]
Fixed~
Also made it match the other notices that appear under posts and made the width 'fit-content' instead of letting it span the entire pageeee
![firefox_CEPpcw7gKX](https://user-images.githubusercontent.com/91846001/163652981-d7dc5dde-5588-440f-aa13-2cc550c39287.png)
