### ISSUE TITLE
Changes to stats page

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#8]
Due to https://github.com/zwagoth/e621ng/commit/7d287057c4281b0bb20f6e5cbdddc898d9ed54b3 the `.rounded` selectors will have to be changed to `.stats-rounded` [on these lines](https://github.com/mandorinn/eSix-Cafe/blob/main/release/eSixCafe.user.css#L2472-L2477). 

The change isn't live on the site yet, but I'm making this issue while I remember.

**Comment by mandorinn** [comment]
Fixed!
For now I just added .stats-rounded to the .rounded selector instead of outright replacing itttttt
When the change goes live the .rounded selector will get removed if it causes issuesss~
