### ISSUE TITLE
Pending replacements don't have a red background

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#9]
Pending replacements on the [Post Replacements](https://e621.net/post_replacements) page don't have a red background to distinguish them from the approved replacements.

![image](https://user-images.githubusercontent.com/102884856/176502209-9f2166e8-5f54-41cf-a2a9-16c5e70de3ee.png)

How it looks with vanilla e621.
![image](https://user-images.githubusercontent.com/102884856/176502154-9a0a5ae7-2603-45bf-a4d3-a419baf9da98.png)

The background color is defined here
![image](https://user-images.githubusercontent.com/102884856/176503196-7cbacb14-ffbb-4278-a35a-60ee825907a3.png)

But it looks like this part is overriding it:
![image](https://user-images.githubusercontent.com/102884856/176503343-be90dde9-2970-41b3-b741-b4af6fb72bf8.png)

**Comment by mandorinn** [comment]
Just now got around to fixing ittttt, should be fine now~

**Comment by faucetlol** [comment]
![image](https://user-images.githubusercontent.com/102884856/176650940-7d63485c-1fd7-4d37-8f08-0c19f02a1c73.png)

Only seems to be doing part of it - unless that's intentional?

**Comment by mandorinn** [comment]
Yeah it's intentional!
I can make the red cover the entire area again if you think it looks better thoooo~
